export const TASK_CREATE = "TASK_CREATE";
export const TASK_PROCESS = "TASK_PROCESS";
export const TASK_PROCESS_CANCEL_ALL = "TASK_CANCEL_ALL";
export const TASK_PROCESS_ALL = "TASK_PROCESS_ALL";
export const TASK_PROCESS_START = "TASK_PROCESS_START";
export const TASK_PROCESS_ERROR = "TASK_PROCESS_ERROR";
export const TASK_PROCESS_DONE = "TASK_PROCESS_DONE";
export const TASK_PROCESS_RESET = "TASK_PROCESS_RESET";

export const statuses = {
  IDLE: "IDLE",
  STARTED: "STARTED",
  DONE: "DONE",
  FAILED: "FAILED"
};
